workflows:
  iris-ios-build:
    name: IRIS AI iOS Build
    max_build_duration: 30
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "com.mall.iris"
        APP_NAME: "IRIS"
    scripts:
      - name: Install dependencies
        script: |
          echo "No dependencies to install"
      - name: Build .ipa
        script: |
          xcodebuild clean -workspace IRIS.xcworkspace -scheme IRIS -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcodebuild archive -workspace IRIS.xcworkspace -scheme IRIS -sdk iphoneos -archivePath $CM_BUILD_DIR/IRIS.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/IRIS.xcarchive -exportPath $CM_BUILD_DIR/export -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - $CM_BUILD_DIR/export/*.ipa
