workflows:
  ios-build:
    name: IRIS Build
    environment:
      xcode: latest
    scripts:
      - name: Build IRIS app
        script: |
          xcodebuild -project IRIS.xcodeproj \
            -scheme IRIS \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $HOME/build/IRIS.xcarchive archive
    artifacts:
      - build/IRIS.xcarchive
